server.port=9000

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/musicstream
spring.datasource.username=sergio
spring.datasource.password=1234
spring.datasource.driver-className=org.postgresql.Driver

# JPA / Hibernate
# 'update' creará las tablas si no existen, pero no borrará los datos existentes al reiniciar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


server.servlet.session.timeout=30m

# Forzar codificación UTF-8 para Thymeleaf
spring.thymeleaf.encoding=UTF-8
spring.messages.encoding=UTF-8
